name: omero
channels:
  - ome
  - defaults
dependencies:
  - jupyterlab=2.2.6
  - notebook=6.1.4
  - numpy=1.19.1
  - omero-py=5.8.2
  - pandas=1.1.2
  - pip=20.2.3
  - python=3.8.5
  - tifffile=2020.9.22
  - pip:
    - ome-model==6.2.1
